server:
  error:
    include-stacktrace: never
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/login
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: #your google email (There is a way to create a generic passowrd to use the gmail server to send email)
    password: #your google password
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
